FILES = Aggressive.o BadCondition.o BuildTrackCommand.o CarBuilder.o CarPart.o Cautious.o Championship.o ChangeTires.o Chassie.o Cloudy.o ConcreteTrack.o ConstructorsChampionship.o CreateTeamCommand.o DriversChampionship.o Engine.o GoodCondition.o Hairpin.o HardCompound.o Hub.o main.o MediumCompound.o Memento.o NinetyDegreeTurn.o OKCondition.o Race.o RaceCar.o RaceCarBuilder.o RaceConditionCommand.o RacingTeam.o Rainy.o SeasonalResultsCommand.o Sensible.o SingletonChampionship.o SlightTurn.o SoftCompound.o StartRaceCommand.o Straight.o Sunny.o Suspension.o S_Section.o Team.o TeamState.o TeamStateCaretaker.o Tire.o TireCompound.o TireState.o Track.o TrackBuilder.o TrackMaker.o TrackSection.o Weather.o Wing.o 

main: $(FILES)
	g++ -o main $(FILES)

Aggressive.o:
	g++ -c -g Aggressive.cpp

BadCondition.o:
	g++ -c -g BadCondition.cpp

BuildTrackCommand.o:
	g++ -c -g BuildTrackCommand.cpp

CarBuilder.o:
	g++ -c -g CarBuilder.cpp

CarPart.o:
	g++ -c -g CarPart.cpp

Cautious.o:
	g++ -c -g Cautious.cpp

Championship.o:
	g++ -c -g Championship.cpp

ChangeTires.o:
	g++ -c -g ChangeTires.cpp

Chassie.o:
	g++ -c -g Chassie.cpp

Cloudy.o:
	g++ -c -g Cloudy.cpp

ConcreteTrack.o:
	g++ -c -g ConcreteTrack.cpp

ConstructorsChampionship.o:
	g++ -c -g ConstructorsChampionship.cpp

CreateTeamCommand.o:
	g++ -c -g CreateTeamCommand.cpp

DriversChampionship.o:
	g++ -c -g DriversChampionship.cpp

Engine.o:
	g++ -c -g Engine.cpp

GoodCondition.o:
	g++ -c -g GoodCondition.cpp

Hairpin.o:
	g++ -c -g Hairpin.cpp

HardCompound.o:
	g++ -c -g HardCompound.cpp

Hub.o:
	g++ -c -g Hub.cpp

main.o:
	g++ -c -g main.cpp

MediumCompound.o:
	g++ -c -g MediumCompound.cpp

Memento.o:
	g++ -c -g Memento.cpp

NinetyDegreeTurn.o:
	g++ -c -g NinetyDegreeTurn.cpp

OKCondition.o:
	g++ -c -g OKCondition.cpp

Race.o:
	g++ -c -g Race.cpp

RaceCar.o:
	g++ -c -g RaceCar.cpp

RaceCarBuilder.o:
	g++ -c -g RaceCarBuilder.cpp

RaceConditionCommand.o:
	g++ -c -g RaceConditionCommand.cpp

RacingTeam.o:
	g++ -c -g RacingTeam.cpp

Rainy.o:
	g++ -c -g Rainy.cpp

SeasonalResultsCommand.o:
	g++ -c -g SeasonalResultsCommand.cpp

Sensible.o:
	g++ -c -g Sensible.cpp

SingletonChampionship.o:
	g++ -c -g SingletonChampionship.cpp

SlightTurn.o:
	g++ -c -g SlightTurn.cpp

SoftCompound.o:
	g++ -c -g SoftCompound.cpp

StartRaceCommand.o:
	g++ -c -g StartRaceCommand.cpp

Straight.o:
	g++ -c -g Straight.cpp

Sunny.o:
	g++ -c -g Sunny.cpp

Suspension.o:
	g++ -c -g Suspension.cpp

S_Section.o:
	g++ -c -g S_Section.cpp

Team.o:
	g++ -c -g Team.cpp

TeamState.o:
	g++ -c -g TeamState.cpp

TeamStateCaretaker.o:
	g++ -c -g TeamStateCaretaker.cpp

Tire.o:
	g++ -c -g Tire.cpp

TireCompound.o:
	g++ -c -g TireCompound.cpp

TireState.o:
	g++ -c -g TireState.cpp

Track.o:
	g++ -c -g Track.cpp

TrackBuilder.o:
	g++ -c -g TrackBuilder.cpp

TrackMaker.o:
	g++ -c -g TrackMaker.cpp

TrackSection.o:
	g++ -c -g TrackSection.cpp

Weather.o:
	g++ -c -g Weather.cpp

Wing.o:
	g++ -c -g Wing.cpp

run: main
	./main

clean:
	rm main *.o
	clear

