FILES = BadCondition.o CarBuilder.o CarPart.o ChangeTires.o Chassie.o Engine.o GoodCondition.o HardCoumpound.o Hub.o main.o MediumCompound.o OKCondition.o RaceCar.o RaceCarBuilder.o SoftCompound.o Suspension.o Team.o Tire.o TireCompound.o TireState.o Wing.o 

main: $(FILES)
	g++ -o main $(FILES)

BadCondition.o:
	g++ -c -g BadCondition.cpp

CarBuilder.o:
	g++ -c -g CarBuilder.cpp

CarPart.o:
	g++ -c -g CarPart.cpp

ChangeTires.o:
	g++ -c -g ChangeTires.cpp

Chassie.o:
	g++ -c -g Chassie.cpp

Engine.o:
	g++ -c -g Engine.cpp

GoodCondition.o:
	g++ -c -g GoodCondition.cpp

HardCoumpound.o:
	g++ -c -g HardCoumpound.cpp

Hub.o:
	g++ -c -g Hub.cpp

main.o:
	g++ -c -g main.cpp

MediumCompound.o:
	g++ -c -g MediumCompound.cpp

OKCondition.o:
	g++ -c -g OKCondition.cpp

RaceCar.o:
	g++ -c -g RaceCar.cpp

RaceCarBuilder.o:
	g++ -c -g RaceCarBuilder.cpp

SoftCompound.o:
	g++ -c -g SoftCompound.cpp

Suspension.o:
	g++ -c -g Suspension.cpp

Team.o:
	g++ -c -g Team.cpp

Tire.o:
	g++ -c -g Tire.cpp

TireCompound.o:
	g++ -c -g TireCompound.cpp

TireState.o:
	g++ -c -g TireState.cpp

Wing.o:
	g++ -c -g Wing.cpp

run: main
	./main

clean:
	rm main *.o
	clear

